### ISSUE TITLE
Interactive-Button GameObject Glitch 

### ISSUE THREAD

**Issue by alhasacademy96** [Kinds-of-Intelligence-CFI/animal-ai-unity-project#18]
Upon triggering the blue button to move back and forwards within a quick animation time, the button disappears from the overall gameobject Pillar-Button. This is most likely due to the move/reset animation duration times happening too quick one after the other, which forces the child-mesh to disappear inside the pillar-button parent mesh. 

Example config: 

```
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: Pillar-Button
      positions:
      - !Vector3 {x: 25, y: 0, z: 30}
      moveDurations: [0.1]
      resetDurations: [1.0]
```

Priority set to **high**.
